export const dummyCandidates = [
  {
    id: 1,
    name: "Yukiko Tanaka",
    email: "yukiko.tanaka@mail.com",
    phone: "08123123301",
    date_of_birth: new Date("1995-01-10"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/yukiko",
    gender: "Female",
  },
  {
    id: 2,
    name: "Rina Sasaki",
    email: "rina.sasaki@mail.com",
    phone: "08123123302",
    date_of_birth: new Date("1992-03-15"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/rina",
    gender: "Female",
  },
  {
    id: 3,
    name: "Haruto Yamamoto",
    email: "haruto.yamamoto@mail.com",
    phone: "08123123303",
    date_of_birth: new Date("1990-07-22"),
    domicile: "Surabaya",
    linkedin_url: "https://www.linkedin.com/in/haruto",
    gender: "Male",
  },
  {
    id: 4,
    name: "Sakura Kobayashi",
    email: "sakura.kobayashi@mail.com",
    phone: "08123123304",
    date_of_birth: new Date("1998-11-05"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/sakura",
    gender: "Female",
  },
  {
    id: 5,
    name: "Kaito Nakamura",
    email: "kaito.nakamura@mail.com",
    phone: "08123123305",
    date_of_birth: new Date("1993-05-18"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/kaito",
    gender: "Male",
  },
  {
    id: 6,
    name: "Aoi Suzuki",
    email: "aoi.suzuki@mail.com",
    phone: "08123123306",
    date_of_birth: new Date("1996-09-12"),
    domicile: "Yogyakarta",
    linkedin_url: "https://www.linkedin.com/in/aoi",
    gender: "Female",
  },
  {
    id: 7,
    name: "Ren Sato",
    email: "ren.sato@mail.com",
    phone: "08123123307",
    date_of_birth: new Date("1994-02-28"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/ren",
    gender: "Male",
  },
  {
    id: 8,
    name: "Hana Fujimoto",
    email: "hana.fujimoto@mail.com",
    phone: "08123123308",
    date_of_birth: new Date("1997-08-19"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/hana",
    gender: "Female",
  },
  {
    id: 9,
    name: "Yuto Takahashi",
    email: "yuto.takahashi@mail.com",
    phone: "08123123309",
    date_of_birth: new Date("1991-12-03"),
    domicile: "Surabaya",
    linkedin_url: "https://www.linkedin.com/in/yuto",
    gender: "Male",
  },
  {
    id: 10,
    name: "Mio Kudo",
    email: "mio.kudo@mail.com",
    phone: "08123123310",
    date_of_birth: new Date("1999-04-27"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/mio",
    gender: "Female",
  },
  {
    id: 11,
    name: "Takumi Ishikawa",
    email: "takumi.ishikawa@mail.com",
    phone: "08123123311",
    date_of_birth: new Date("1990-06-14"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/takumi",
    gender: "Male",
  },
  {
    id: 12,
    name: "Emi Okada",
    email: "emi.okada@mail.com",
    phone: "08123123312",
    date_of_birth: new Date("1995-09-09"),
    domicile: "Surabaya",
    linkedin_url: "https://www.linkedin.com/in/emi",
    gender: "Female",
  },
  {
    id: 13,
    name: "Shota Mori",
    email: "shota.mori@mail.com",
    phone: "08123123313",
    date_of_birth: new Date("1992-11-21"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/shota",
    gender: "Male",
  },
  {
    id: 14,
    name: "Aya Watanabe",
    email: "aya.watanabe@mail.com",
    phone: "08123123314",
    date_of_birth: new Date("1996-03-30"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/aya",
    gender: "Female",
  },
  {
    id: 15,
    name: "Kenta Hasegawa",
    email: "kenta.hasegawa@mail.com",
    phone: "08123123315",
    date_of_birth: new Date("1993-10-11"),
    domicile: "Yogyakarta",
    linkedin_url: "https://www.linkedin.com/in/kenta",
    gender: "Male",
  },
  {
    id: 16,
    name: "Riko Matsumoto",
    email: "riko.matsumoto@mail.com",
    phone: "08123123316",
    date_of_birth: new Date("1997-12-07"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/riko",
    gender: "Female",
  },
  {
    id: 17,
    name: "Daiki Shimizu",
    email: "daiki.shimizu@mail.com",
    phone: "08123123317",
    date_of_birth: new Date("1991-05-24"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/daiki",
    gender: "Male",
  },
  {
    id: 18,
    name: "Nana Fujita",
    email: "nana.fujita@mail.com",
    phone: "08123123318",
    date_of_birth: new Date("1994-08-16"),
    domicile: "Surabaya",
    linkedin_url: "https://www.linkedin.com/in/nana",
    gender: "Female",
  },
  {
    id: 19,
    name: "Ryota Kimura",
    email: "ryota.kimura@mail.com",
    phone: "08123123319",
    date_of_birth: new Date("1990-02-02"),
    domicile: "Jakarta",
    linkedin_url: "https://www.linkedin.com/in/ryota",
    gender: "Male",
  },
  {
    id: 20,
    name: "Mika Nakagawa",
    email: "mika.nakagawa@mail.com",
    phone: "08123123320",
    date_of_birth: new Date("1998-07-29"),
    domicile: "Bandung",
    linkedin_url: "https://www.linkedin.com/in/mika",
    gender: "Female",
  },
];
