import { IJobDetails } from "@/types/job";

export const dummyJob: IJobDetails[] = [
  {
    id: 1,
    companyName: "Rakamin",
    companyLogo: "/short-logo.png",
    jobTitle: "UX Designer",
    jobType: "Full Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Selatan",
    minSalary: "7000000",
    maxSalary: "15000000",
    jobStatus: "Active",
    startedAt: new Date("2025-10-01"),
  },
  {
    id: 2,
    companyName: "Danamon",
    companyLogo: "/short-logo.png",
    jobTitle: "Full Stack Developer",
    jobType: "Full Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Pusat",
    minSalary: "5500000",
    maxSalary: "7000000",
    jobStatus: "Inactive",
    startedAt: new Date("2025-10-02"),
  },
  {
    id: 3,
    companyName: "Danamon",
    companyLogo: "/short-logo.png",
    jobTitle: "Full Stack Developer",
    jobType: "Full Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Pusat",
    minSalary: "5500000",
    maxSalary: "7000000",
    jobStatus: "Inactive",
    startedAt: new Date("2025-10-03"),
  },
  {
    id: 4,
    companyName: "Danamon",
    companyLogo: "/short-logo.png",
    jobTitle: "Full Stack Developer",
    jobType: "Part Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Pusat",
    minSalary: "5500000",
    maxSalary: "7000000",
    jobStatus: "Active",
    startedAt: new Date("2025-10-04"),
  },
  {
    id: 5,
    companyName: "Danamon",
    companyLogo: "/short-logo.png",
    jobTitle: "Full Stack Developer",
    jobType: "Full Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Pusat",
    minSalary: "5500000",
    maxSalary: "7000000",
    jobStatus: "Active",
    startedAt: new Date("2025-10-05"),
  },
  {
    id: 6,
    companyName: "Danamon",
    companyLogo: "/short-logo.png",
    jobTitle: "Full Stack Developer",
    jobType: "Part Time",
    jobDesc: "Ini adalah kumpulan jobdesc",
    placement: "Jakarta Pusat",
    minSalary: "5500000",
    maxSalary: "7000000",
    jobStatus: "Draft",
    startedAt: new Date("2025-10-06"),
  },
];
